apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: services
  namespace: app
spec:
  releaseName: services
  chart:
    spec:
      chart: serviceA
      sourceRef:
        kind: HelmRepository
        name: app
        namespace: flux-system
      version: "1.0"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    menu-service:
      image:
        tag: "main"
      podAnnotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "serviceA"
        dapr.io/app-port: "80"
