apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-a
  namespace: app
spec:
  releaseName: services
  chart:
    spec:
      chart: service-a
      sourceRef:
        kind: HelmRepository
        name: app
        namespace: flux-system
      version: "0.1.0"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: "main"
    podAnnotations:
      dapr.io/enabled: "true"
      dapr.io/app-id: "service-a"
      dapr.io/app-port: "80"
