apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "policies": [
        {
          "vhost": "/",
          "name": "tenants",
          "pattern": ".*Tenant*.",
          "apply-to": "exchanges",
          "definition": {"federation-upstream-set":"all"}
          "priority": 0
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ]
    }
